import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';

const ForceChangePassword = () => {
    const { token, updateUser } = useAuth();
    const navigate = useNavigate();
    
    const [password, setPassword] = useState('');
    const [confirm, setConfirm] = useState('');
    const [error, setError] = useState('');
    const [loading, setLoading] = useState(false);

    const handleSubmit = async (e) => {
        e.preventDefault();
        setError('');

        if (password.length < 6) {
            return setError('Password must be at least 6 characters.');
        }
        if (password !== confirm) {
            return setError('Passwords do not match.');
        }

        setLoading(true);

        try {
            const response = await fetch('http://localhost:5000/api/auth/change-password', {
                method: 'PUT',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${token}`
                },
                body: JSON.stringify({ newPassword: password })
            });

            const data = await response.json();

            if (response.ok) {
                // Update local context to remove restriction
                updateUser({ requires_password_change: false });
                navigate('/doctor/dashboard', { replace: true });
            } else {
                setError(data.message || 'Failed to update password.');
            }
        } catch (err) {
            setError('Server error while saving password.');
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="min-h-screen flex items-center justify-center bg-slate-950 p-6 relative overflow-hidden">
            <div className="absolute top-1/2 left-1/2 w-[800px] h-[800px] bg-emerald-500/10 rounded-full blur-[120px] -translate-x-1/2 -translate-y-1/2 pointer-events-none"></div>

            <div className="bg-slate-900 border border-slate-800 rounded-3xl p-10 max-w-md w-full shadow-2xl relative z-10 animate-in fade-in zoom-in-95 duration-500">
                <div className="mx-auto w-16 h-16 bg-blue-500/20 rounded-2xl flex items-center justify-center mb-6 border border-blue-500/30">
                    <svg className="w-8 h-8 text-blue-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
                    </svg>
                </div>
                
                <h1 className="text-3xl font-extrabold text-white text-center mb-2 tracking-tight">Security Alert</h1>
                <p className="text-slate-400 text-center mb-8 text-sm px-4">
                    Your account was generated by an Administrator. You must update your temporary password to secure your account.
                </p>

                {error && (
                    <div className="mb-6 bg-red-500/10 border border-red-500/50 rounded-xl p-4 text-red-500 text-sm font-semibold text-center">
                        {error}
                    </div>
                )}

                <form onSubmit={handleSubmit} className="space-y-5">
                    <div>
                        <label className="block text-sm font-semibold text-slate-300 mb-1.5">New Password</label>
                        <input 
                            type="password" 
                            name="password"
                            value={password}
                            onChange={(e) => setPassword(e.target.value)}
                            required
                            className="w-full bg-slate-950 border border-slate-800 rounded-xl px-4 py-3 text-white focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500 transition-all outline-none"
                            placeholder="Must be at least 6 characters"
                        />
                    </div>
                    <div>
                        <label className="block text-sm font-semibold text-slate-300 mb-1.5">Confirm Password</label>
                        <input 
                            type="password" 
                            name="confirm"
                            value={confirm}
                            onChange={(e) => setConfirm(e.target.value)}
                            required
                            className="w-full bg-slate-950 border border-slate-800 rounded-xl px-4 py-3 text-white focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500 transition-all outline-none"
                            placeholder="Re-type your password"
                        />
                    </div>

                    <button 
                        type="submit" 
                        disabled={loading}
                        className="w-full bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-bold py-3.5 px-4 rounded-xl transition-all shadow-[0_0_20px_rgba(52,211,153,0.3)] hover:shadow-[0_0_30px_rgba(52,211,153,0.5)] mt-4 hover:-translate-y-0.5"
                    >
                        {loading ? 'Securing Account...' : 'Save & Continue to Dashboard'}
                    </button>
                    
                    <p className="text-xs text-slate-500 text-center mt-6">
                        You will not be able to access the system until your password is changed.
                    </p>
                </form>
            </div>
        </div>
    );
};

export default ForceChangePassword;
